### ISSUE TITLE
entrypoint chown

### ISSUE THREAD

**Issue by gajowi** [Unidata/tomcat-docker#33]
I was just bitten by the new chown in the entrypoint script. I am writing a hyrax/olfs Dockerfile which builds on this container and need a custom entrypoint to meet olfs needs. The upstream change left me with tomcat failing to run because it could not write files/directories owned by root.

The offending change is https://github.com/Unidata/tomcat-docker/commit/90ca1412754d54aa3505128eaef5d0841023e5e4

I've been able to work around the issue by copying the chown into my own custom entrypoint but I think it would be better to put the chown back in the Dockerfile, not the entrypoint.

Another possible solution would be to add something like:
```
for file in /entrypoint.d/*.sh; do
   test -x $file && ./$file
done
```
(untested - would need more checks).  In that case a downstream project could extend the entrypoint without over-riding it. The official postgres docker setup does something along these lines to instantiate a database in a configurable way.

**Comment by julienchastang** [comment]
Pull the latest `unidata/thredds-docker` container from dockerhub. You should not be running into `chown` problems. Here is what happened: 81798b0 broke the inheriting containers in that they could start tomcat via the `entrypoint.sh` but since the thredds-docker container was starting tomcat via `catalina.sh` instead of `start-tomcat.sh`, the `chown` command in the conditional (`if [ "$1" = 'start-tomcat.sh' ]`) was getting bypassed. `catalina.sh` was getting started with the final `exec "$@"`.  I have since fixed this problem with `if [ "$1" = 'start-tomcat.sh' ] || [ "$1" = 'catalina.sh' ]; then`. See the new `entrypoint.sh` for details.

It took the dockerhub automated builds all day to catch up since I have linked the projects via the automated build process. It finally caught up in the late afternoon Mountain Time.

Running `chown` in the `entrypoint.sh` and not the `Dockerfile` is the way to do it, IMO. You know your permissions will be OK at container run time.

Man, that commit (81798b0) really screwed things up at least for a while. Can you confirm that chown problems are solved by pulling the latest container so we can hopefully close this issue.

**Comment by gajowi** [comment]
The latest unidata/thredds-docker container from dockerhub is fine. My problem is with the underlying tomcat-docker and how I am reusing it for another tomcat hosted application. The tomcat-docker container is a nice piece of work in its own right so I may as well reuse it if I can - particularly for a context related to data service, OPeNDAP and THREDDS where we can build community and support one another. My problem is that the way the entrypoint is used makes my downstream entrypoint customization fragile.

I need to use the entrypoint to alter files as root before using gosu to drop pivilege so it helps me _not_ to require that I copy across all your entrypoint content.

By the way, I've read some of the verbose discussion on ADD and COPY and the current need for chown and the bloat it causes.  I think it is OK to chown in the Dockerfile but best to limit to content that needs it. Read-only content can all be owned by root (surely). It is just a limited set of runtime content that needs tomcat ownership. I suspect chown in the entrypoint causes the same bloat at container startup in any case :-P

As I say, I have a workaround, but would appreciate an upstream change. Would you be open to a PR looping over scripts in /entrypoint.d/ ? Then you could change how the chown is done (or not) without downstream impact.

**Comment by julienchastang** [comment]
Can you simply override with your own `entrypoint.sh` in the inherited container? Its like in OOP when you override behavior. That's what I do for ramadda-docker. (Yeah, I read that `chown` bloat discussion too. That also was part of the motivation.)

**Comment by gajowi** [comment]
I'm getting back to this in another context. I've been running instances of thredds-docker with a custom tomcat-users.xml and server.xml mapped in at runtime.  In that case the chown and chmod break my workflow. However I can override the entrypoint too in the same manner so I don't need an upstream fix (though I do have the difficulty of missing upstream changes ).

Probably I should add a layer starting with 'FROM unidata/thredds-docker' and bake my customizations into my own layer.

In both cases I have a workable solution so I'm happy to have this issue closed.
