### ISSUE TITLE
Unique tags for new builds?

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/tomcat-docker#86]
It appears that new Tomcat containers are built without unique tags (see screen grab below). 

If unique tags were generated for new builds, it would allow containers that depend on the Unidata Tomcat container (like Axiom's [ncwms container](https://hub.docker.com/r/axiom/ncwms)) to rebuild automagically.

![2020-03-09_10-44-02](https://user-images.githubusercontent.com/1872600/76226072-bb90d600-61f3-11ea-8969-51705eb5baf2.png)

**Comment by julienchastang** [comment]
This scheme is no different from the parent container and is apparently customary in Dockerland (correct me if I am wrong).  In fact, I keep referencing the same parent Tomcat  (e.g.,`tomcat:8.5-jdk8-openjdk`) tag and these changes are permeating through simply when I rebuild. There is already the capability to do these automagic rebuilds with DockerHub (I used to use it) -- they must look at the digest number instead. I don't recommend going the automagic route though. You can get caught off guard by upstream changes that break your container. That's why I turned that feature off.

**Comment by rsignell-usgs** [comment]
@julienchastang , okay, thanks for the education!  😄
ping @kwilcox
